# Generated by Django 5.2.1 on 2025-06-25 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_proveedor_contacto_alter_proveedor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d+$', message='Solo se permiten números.')]),
        ),
    ]
