# Generated by Django 5.2.1 on 2025-06-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_proveedor_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
    ]
