# Generated by Django 5.2.1 on 2025-06-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_compradorfiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradorfiel',
            name='rut',
            field=models.CharField(default='TEMP-RUT-001', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
