# Generated by Django 5.2.1 on 2025-07-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ventas.proveedor'),
            preserve_default=False,
        ),
    ]
