# Generated by Django 5.2.3 on 2025-07-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
